default: &default
  adapter: postgresql
  encoding: utf8
  pool: 5
  timeout: 5000


development:
  <<: *default
  database: my_database_development

test:
  <<: *default
  database: my_database_test

production:
  <<: *default
  database: my_database_production
