# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75a66e0e2e808bb5e17c718b051ac500f1855a231df84cdae814ebe7aacfa5dbfb001ac3c860dd93316d95bffb2a31c2090d989de4ec85723cf85c37d58813d8

test:
  secret_key_base: 8fb9f75c678b96d25f7e07094d65aca1f3396240785f2a50779361e9ed020de25008dc998f8237e0ba928dd31b50b0d5df3577ad53e5b81a43ef9064409a5314

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
